Update sync-fork-with-upstream.yaml
fix workflow

diff --git a/.github/workflows/sync-fork-with-upstream.yaml b/.github/workflows/sync-fork-with-upstream.yaml
--- a/.github/workflows/sync-fork-with-upstream.yaml
+++ b/.github/workflows/sync-fork-with-upstream.yaml
@@ -12,10 +12,6 @@ on:
         description: 'Fork Sync Test Mode'
         type: boolean
         default: false
-        
-permissions:
-  id-token: write
-  contents: read
 
 jobs:
   sync_latest_from_upstream:
@@ -50,14 +46,20 @@ jobs:
       if: steps.sync.outputs.has_new_commits == 'true'
       run: echo "New commits were found to sync."
       
-    # Call build and release workflow if we have new commits
-    - name: Call build and release workflow
-      if: steps.sync.outputs.has_new_commits == 'true'
-      uses: gz-42/OpenDAoC-Database/.github/workflows/build-and-release.yaml@master
-    
     - name: No new commits
       if: steps.sync.outputs.has_new_commits == 'false'
       run: echo "There were no new commits."
       
     - name: Show value of 'has_new_commits'
       run: echo ${{ steps.sync.outputs.has_new_commits }}
+
+    #If there is no new commit then exit fail the action
+    - name: If no new commits, fail the action
+      if: steps.sync.outputs.has_new_commits == 'false'
+      run: exit 1
+
+  build-and-release:
+    need: sync_latest_from_upstream
+    name: build-and-release
+    run-on: ubuntu-latest
+    uses: gz-42/OpenDAoC-Database/.github/workflows/build-and-release.yaml@master
